platform :ios, '7.0'

target :BonusStore do
    pod 'AFNetworking',     '~> 3.0.0'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'JPush',            '~> 2.1.9'
    pod 'UMengAnalytics',   '~> 4.1.0'
    pod 'UMengSocial',      '~> 5.0'
    pod 'SobotFramework',   '~> 1.4.0'
    pod 'BaiduMobStat',     '~> 4.1.0'
    pod 'MJRefresh'
end

target :BonusStore_Dev do
    pod 'AFNetworking',     '~> 3.0.0'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'JPush',            '~> 2.1.9'
    pod 'UMengAnalytics',   '~> 4.1.0'
    pod 'UMengSocial',      '~> 5.0'
    pod 'SobotFramework',   '~> 1.4.0'
    pod 'BaiduMobStat',     '~> 4.1.0'
    pod 'MJRefresh'
end

